version: "3"
services:
  frontend:
    build:
      context : ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5000:5000"
    env_file:
      - ./Frontend/.env
  backend:
    build:
      context : ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    env_file:
      - ./Backend/.env
  model:
    build:
      context : ./Model
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "5001:5001"
      - "5000:5000"
    env_file:
      - ./Model/.env