version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: toxicity_prometheus
    ports:
      - 9090:9090
    volumes:
      - "C:/Users/gauti/OneDrive - Efrei/Documents/S9/Data Engineering/ToxicityProject/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: always
  frontend:
    container_name: toxicity_frontende
    build: ./Frontend
    restart: always
    ports:
      - "5001:5001"
  backend:
    container_name: toxicity_backend
    build:
      context : ./Backend
    restart: always
    ports:
      - "5000:5000"
  model:
    container_name: toxicity_model
    build: ./Model
    restart: always
    ports:
      - "5002:5002"
