version: "3"
services:
  frontend:
    container_name: toxicity_frontend
    build: ./Frontend
    restart: always
    ports:
      - "5001:5001"
  backend:
    container_name: toxicity_backend
    build:
      context : ./Backend
    restart: always
    ports:
      - "5000:5000"
  model:
    container_name: toxicity_model
    build: ./Model
    restart: always
    ports:
      - "5002:5002"